name: Trigger auto deployment for node-todoapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/node-todoapp-AutoDeployTrigger-e5ddf685-4ded-46d9-9688-a6a1e3e98322.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.NODETODOAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NODETODOAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NODETODOAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.NODETODOAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NODETODOAPP_REGISTRY_PASSWORD }}
          containerAppName: node-todoapp
          resourceGroup: pranay201024
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


